catalogo = """
### **Catálogo de Productos**

#### **1. Sillas de Oficina y Gerenciales**
- **Silla Presidencial Mirage 70x70x114 Negra** (ID: 238)  
- **Silla Presidencial Ergonómica de Respaldo Alto Giratorio Ergohuman** (ID: 239)  
- **Silla De Oficina Gerencial Obelisco Lk-1002_Neg** (ID: 241)  
- **Silla Gerencial Libertad Alta Color Negro en Malla** (ID: 243)  
- **Silla De Oficina De Malla Ergonómica Akivoy JYX0091WD - Negro** (ID: 244)  
- **Silla De Oficina Gerencial Akivoy JYX0092WD - Negra** (ID: 245)  
- **Silla Para Oficina Gerencia Collins Alta Negro** (ID: 246)  
- **Silla De Oficina Ejecutiva En Malla Negra Ergonómica** (ID: 247)  
- **Silla Gerencial Domus** (ID: 251)  
- **Silla para Oficina Ejecutiva Libertad** (ID: 255)  
- **Silla De Oficina Gerencial Akivoy JYX-0092** (ID: 259)  
- **Silla De Oficina Escritorio Ergonomica Akivoy JYX0091 - Negra** (ID: 260)  
- **Silla Gerencial De Escritorio Ejecutiva Oficina Ergo JYX0096** (ID: 262)  
- **Silla Ejecutiva Pasadena con Basculante / Base Cromada** (ID: 264)  
- **Silla Para Oficina Gerencial En Malla Negra Pekin** (ID: 265)  
- **Silla de Oficina En Malla Neja** (ID: 267)  
- **Silla de Oficina Giratoria Acolchada Eames Color Negro** (ID: 270)  
- **Silla Interlocutora Isonet Malla** (ID: 271)  
- **Silla Gerencial De Oficina En Malla Negra Brooklyn** (ID: 272)  
- **Silla Gerencial Wynn Sports** (ID: 1416)  
- **Silla De Oficina Gerencial London** (ID: 1648)  
- **Silla Gerencial Ónix** (ID: 10737)  
- **Silla Gerencial Siam** (ID: 10738)  
- **Silla Gerencial Monk** (ID: 10739)  
- **Silla Gerencial Kone** (ID: 10740)  
- **Silla Gerencial Osaka** (ID: 10741)  
- **Silla Presidencial Leaf** (ID: 10762)  
- **Silla Gerencial Soho** (ID: 10763)  
- **Silla Gerencial Opera** (ID: 10834)  
- **Silla Gerencial Saravena** (ID: 10849)  
- **Silla Gerencial Nepal** (ID: 10850)  
- **Silla Gerencial Domus 2.0** (ID: 10853)  
- **Silla Gerencial Berlin** (ID: 10854)  
- **Silla Gerencial Zurich** (ID: 10855)  
- **Silla Gerencial Monza** (ID: 10857)  
- **Silla Gerencial Vienna** (ID: 10858)  
- **Silla Gerencial ErgoKing** (ID: 11025)  
- **Silla Gerencial Titan Pro** (ID: 11027)  
- **Silla Gerencial Ergomax** (ID: 11028)  
- **Silla Gerencial Shanghai 2024** (ID: 11045)  
- **Silla Gerencial Prestige Negra** (ID: 11060)  
- **Silla Gerencial Prestige Blanco** (ID: 11061)  
- **Silla Gerencial Épica** (ID: 11062)  
- **Silla Gerencial Soberana Blanca y Azul** (ID: 11063)  
- **Silla Gerencial Prime** (ID: 11068)  
- **Silla Gerencial Horizonte 3D** (ID: 11069)  
- **Silla Gerencial Horizonte 2D** (ID: 11070)  
- **Silla Gerencial Neo 2D** (ID: 11072)  
- **Silla Gerencial Duty 3D** (ID: 11074)  
- **Silla Gerencial Duty 2D** (ID: 11075)  
- **Silla Gerencial Diamante** (ID: 11076)  
- **Silla Gerencial Emperatriz** (ID: 11078)  
- **Silla Gerencial Stick** (ID: 11079)  
- **Silla Gerencial Budapest** (ID: 11206)  
- **Silla Gerencial Orion** (ID: 11263)  
- **Silla Gerencial Longyi Base Plástica** (ID: 11269)  

---

#### **2. Sillas Gamer**
- **Sofá Gamer Kratos** (ID: 285)  
- **SILLA GAMER RANGER NEGRO BLANCO** (ID: 293)  
- **Silla Gamer Omega Reclinable con Reposa Pies Negra** (ID: 304)  
- **Silla Gamer Doom** (ID: 1298)  
- **Silla Gamer Edifice Gris** (ID: 1301)  
- **Silla Gamer Doom Para Oficina en Cuero Acolchada Giratoria** (ID: 1421)  
- **Silla Gamer Doom Para Oficina Negra Acolchada Roja** (ID: 1422)  
- **Silla Gamer Omega Reclinable con Reposa Pies Negra - Blanca** (ID: 1425)  
- **Silla Gamer Edifice Azul** (ID: 2192)  
- **Silla Gamer Edifice Roja** (ID: 2206)  
- **Silla Gamer Venon Ergonómica Giratoria Reclinable Lk-2367 Roja** (ID: 2211)  
- **Silla Gamer Basic Series Negra** (ID: 2518)  
- **Silla Gamer Ergonómica Reclinable Color Negro - Naranja** (ID: 2532)  
- **Silla Gamer Ergonómica Reclinable Color Negro** (ID: 2533)  
- **Silla Gamer Daytona** (ID: 10827)  
- **Silla Gamer Fenix Roja** (ID: 10828)  
- **Silla Gamer Fenix Blanca** (ID: 10829)  
- **Silla Gamer Stinger Roja** (ID: 10831)  
- **Silla Gamer Stinger Azul** (ID: 10832)  
- **Silla Gamer Stinger Blanca** (ID: 10833)  
- **Silla Gamer Raptor Azul** (ID: 10859)  
- **Silla Gamer Raptor Roja** (ID: 10860)  
- **Silla Gamer Raptor Negra** (ID: 10861)  
- **Silla Gamer Maverick** (ID: 10880)  
- **Silla Gamer Sakai Blanca** (ID: 10881)  
- **Silla Gamer Sakai Roja** (ID: 10882)  
- **Silla Gamer Sakai Negra** (ID: 10883)  
- **Silla Gamer Sakai Azul** (ID: 11032)  
- **Silla Gamer Drake** (ID: 11033)  
- **Silla Gamer Prime** (ID: 11034)  
- **Silla Gamer Fury** (ID: 11035)  
- **Silla Gamer Nova** (ID: 11036)  
- **Silla Gamer Nova Roja y Negra** (ID: 11037)  
- **Silla Gamer Nova Blanco y Negro** (ID: 11038)  
- **Silla Gamer Nova Negra** (ID: 11040)  
- **Silla Gamer Valorant Rojo - Negro** (ID: 11086)  
- **Silla Gamer Valorant Negra** (ID: 11087)  
- **Silla Gamer Valorant Blanco - Negro** (ID: 11088)  
- **Silla Gamer Black Cops** (ID: 11104)  
- **Silla Gamer Warzone** (ID: 11105)  
- **Silla Gamer Kitty** (ID: 11106)  
- **Silla Gamer Overkill** (ID: 11264)  
- **Silla Gamer Militar Creed** (ID: 11265)  

---

#### **3. Sillas para Comedor y Bar**
- **Silla Para comedor Gongga Acolchada Cuero Color Negro** (ID: 307)  
- **Silla Para comedor Gongga Acolchada Cuero Color Blanca** (ID: 308)  
- **Sillas Eames Tradicional patas en madera Agua Marina** (ID: 315)  
- **Silla Para Comedor Master En Polipropileno Color Negro** (ID: 330)  
- **Silla Butaco Tolix Negra Metálica Brillante AKIVOY- Negro** (ID: 332)  
- **Silla Tolix Metálica Negro Hogar Restaurante** (ID: 333)  
- **Silla Tolix Metálica Blanca Hogar Restaurante** (ID: 334)  
- **Silla Tolix Metálica Plata Hogar Restaurante** (ID: 340)  
- **Silla Tulip Pata Cuadrada Negra** (ID: 352)  
- **Silla Tulip Pata Redonda Blanca** (ID: 355)  
- **Silla Eames Tradicional Para Comedor Gris Akivoy** (ID: 356)  
- **Silla Eames Tulip Bar Acolchada Cuero PU Negra AKIVOY** (ID: 359)  
- **Silla Eames Tulip Bar Acolchada Cuero Pu Blanca AKIVOY** (ID: 360)  
- **Silla Bar Gongga Cuero PU Blanca Base Cromada AKIVOY** (ID: 362)  
- **Silla Bar Pizza Alta Polipropileno Negro** (ID: 363)  
- **Silla Bar Pizza Alta** (ID: 364)  
- **BUTACO EAMES TULIP MADERA HAYA - BLANCO** (ID: 366)  
- **BUTACO EAMES TULIP MADERA HAYA - NEGRO** (ID: 367)  
- **BUTACO EAMES MADERA HAYA -BLANCO** (ID: 368)  
- **BUTACO EAMES MADERA HAYA -NEGRO** (ID: 369)  
- **SILLA BAR OPRAH ALTA - NEGRO** (ID: 370)  
- **SILLA BAR OPRAH ALTA - BLANCO** (ID: 371)  
- **Silla Bar Tonik Blanca** (ID: 2498)  
- **Silla Bar Aurora Negra** (ID: 10825)  
- **Silla Bar Aurora Blanca** (ID: 10826)  
- **Silla Bar Bali Negra** (ID: 10875)  
- **Silla Bar Bali Blanca** (ID: 10876)  

---

#### **4. Muebles de Oficina y Escritorios**
- **Escritorio Gamer Mesa De Computo En Madera Blanco** (ID: 1005)  
- **Escritorio Gamer 3 estantes negro** (ID: 1006)  
- **Escritorio en L de oficina Boss Table de cristal Color Negro** (ID: 1356)  
- **Escritorio Joy** (ID: 10812)  
- **Escritorio en L Loix** (ID: 10813)  
- **Escritorio Royal** (ID: 10885)  
- **Escritorio Sprint** (ID: 10887)  
- **Escritorio Swift** (ID: 10888)  
- **Escritorio Sirion** (ID: 10889)  
- **Escritorio en L Takai** (ID: 10890)  

---

#### **5. Muebles de Cocina y Alacenas**
- **Mueble Inferior De Cocina Anita 120 Cm 3 Puertas 1 Cajon Capuchino Hueso** (ID: 1090)  
- **Mueble Gabinete Superior De Cocina Lavinia + Alacena Damasco Negro** (ID: 1101)  
- **Alacena Mueble Auxiliar De Cocina 2 Puertas Aline 197 Cm Capuchino** (ID: 1111)  
- **Mueble Superior Aline + Alacena Damasco Hueso** (ID: 1114)  
- **Mueble Superior Aline + Alacena Capuchino** (ID: 1115)  
- **Alacena Mueble Auxiliar Cocina Kelly Capuchino Hueso** (ID: 1117)  
- **Alacena Mueble Auxiliar Cocina Kelly Blanco Negro** (ID: 1118)  
- **Alacena Mueble Auxiliar Cocina Carine 4 Puertas Cap / Hueso** (ID: 1119)  
- **Alacena Mueble Auxiliar Cocina Carine 4 Puertas Cap /Alme** (ID: 1120)  
- **Alacena Mueble Auxiliar Cocina Carine 4 Puertas Blanco** (ID: 1121)  
- **Alacena Mueble Auxiliar Cocina Cassia 6 Puertas Capuchino** (ID: 1122)  
- **Alacena Mueble Auxiliar Cocina Cassia 6 Puertas Blanco Negro** (ID: 1123)  
- **Alacena Mueble Auxiliar Cocina Magda 6 Puertas Capuchino** (ID: 1125)  
- **Alacena Mueble Auxiliar Cocina Magda 6 Puertas Capuchino Hue** (ID: 1126)  
- **Alacena Mueble Auxiliar Cocina Magda 6 Puertas Damasco Hueso** (ID: 1127)  
- **Alacena Mueble Auxiliar Cocina Lili 4 Puertas Capuchino** (ID: 1128)  
- **Alacena Mueble Auxiliar Cocina Lili 6 Puertas Capuchino** (ID: 1129)  
- **Mueble Superior Cocina 2 Puertas Basculante 120cm Blanco** (ID: 1132)  
- **Mueble Superior Cocina 2 Puertas 80 cm Blanco** (ID: 1136)  
- **Mueble Superior Cocina 1 Puerta 40 cm Blanco** (ID: 1138)  
- **Mueble Inferior Cocina 91 cm Lat Capuchino** (ID: 1142)  
- **Mueble Superior Cocina 120 cm Capuchino Hueso** (ID: 1145)  
- **Mueble Superior Cocina 160 cm BLC Blanco** (ID: 1146)  
- **Alacena Cassia 8 puertas Capuchino** (ID: 1155)  
- **Alacena Cassia 8 puertas Capuchino Almendra** (ID: 1156)  
- **Alacena Multiusos En Madera Blanco 2 Puertas** (ID: 1160)  
- **Alacena Mueble Multifuncional Cocina Valeria 6 Puertas Cap-H** (ID: 1162)  
- **Alacena Mueble Multifuncional Cocina Manu 8 Puertas Cap-H** (ID: 1166)  

---

#### **6. Muebles de Dormitorio y Closets**
- **CAMA SOLTEIRO BLANCO PIES RETRO NATURAL** (ID: 953)  
- **Camarote Litera Con Armario Color Blanco** (ID: 955)  
- **CAMA MULTIFUNCIONAL CJ BLANCO BRILLO FR BLANCO BRILLO** (ID: 957)  
- **Closet Armario Lisboa 6 Puertas 183 Cm * 147 Cm Blanco** (ID: 427)  
- **Closet Armario Lisboa 4 Puertas 183 cm * 98,5 cm Blanco** (ID: 428)  
- **Closet Armario Lisboa 3 Puertas 183 cm * 74 cm Capuchino** (ID: 431)  
- **Closet Armario Lisboa 3 Puertas 183 cm * 74 cm Blanco** (ID: 432)  
- **ARMARIO MULTIFUNCIONAL BLANCO PARA BAÑO** (ID: 434)  
- **Closet Tokio 6 Puertas 190 cm * 164 cm Capuchino** (ID: 1151)  
- **Closet Armario Tokio 6 Puertas 190 Cm * 164 Cm Cap - Hue** (ID: 1169)  

---

#### **7. Muebles de Entretenimiento y TV**
- **Panel para Tv Francia Hasta 55” pulgadas 106 cm * 136 cm** (ID: 978)  
- **Centro De Entretenimiento Colon De 55 Pulgadas Duna / Negro** (ID: 984)  
- **Centro De Entretenimiento Colon De 55 Pulgadas Blanco / Arcila** (ID: 985)  
- **Panel Tokyo Para TV 60 Blanco** (ID: 990)
"""